[toolchain]
channel = "nightly"
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-std",
  "rust-docs",
  "rust-analyzer",
  "clippy",
  "miri",
  "rust-src",
  "llvm-tools",
]
targets = [
  "thumbv7em-none-eabi",
  "thumbv7em-none-eabihf",
  "thumbv6m-none-eabi",
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-gnu",
  "x86_64-pc-windows-msvc",
]
