# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ads.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'ads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tads.proto\x12\x03\x61\x64s\"\x9f\x02\n\tAdsSample\x12\x17\n\x0fleadOffPositive\x18\x01 \x01(\r\x12\x17\n\x0fleadOffNegative\x18\x02 \x01(\r\x12\x0c\n\x04gpio\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x11\x12\x14\n\x07\x61\x63\x63\x65l_x\x18\x05 \x01(\x02H\x00\x88\x01\x01\x12\x14\n\x07\x61\x63\x63\x65l_y\x18\x06 \x01(\x02H\x01\x88\x01\x01\x12\x14\n\x07\x61\x63\x63\x65l_z\x18\x07 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06gyro_x\x18\x08 \x01(\x02H\x03\x88\x01\x01\x12\x13\n\x06gyro_y\x18\t \x01(\x02H\x04\x88\x01\x01\x12\x13\n\x06gyro_z\x18\n \x01(\x02H\x05\x88\x01\x01\x42\n\n\x08_accel_xB\n\n\x08_accel_yB\n\n\x08_accel_zB\t\n\x07_gyro_xB\t\n\x07_gyro_yB\t\n\x07_gyro_z\"R\n\x0c\x41\x64sDataFrame\x12\n\n\x02ts\x18\x01 \x01(\x04\x12\x15\n\rpacketCounter\x18\x02 \x01(\x04\x12\x1f\n\x07samples\x18\x03 \x03(\x0b\x32\x0e.ads.AdsSampleB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ADSSAMPLE']._serialized_start=19
  _globals['_ADSSAMPLE']._serialized_end=306
  _globals['_ADSDATAFRAME']._serialized_start=308
  _globals['_ADSDATAFRAME']._serialized_end=390
# @@protoc_insertion_point(module_scope)
